//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmpHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmpHelper.LibraryResources", typeof(LibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (campaign 
        ///	(beat_num 0 kUnlockArena World1) 
        ///	(beat_num 0 kUnlockArena World2) 
        ///	(beat_num 0 kUnlockArena World3) 
        ///	(beat_num 0 kUnlockArena PERFECTBRAIN) 
        ///	(beat_num 0 kUnlockArena WETWARE) 
        ///	(play_num_qp 1 kUnlockPowerup autocatcher) 
        ///	(play_num 2 kUnlockExtraSong PHANTOMS) 
        ///	(beat_num 0 kUnlockArena DREAMER) 
        ///	(beat_num 0 kUnlockArena RECESSION) 
        ///	(beat_num 0 kUnlockArena DONOTRETREAT) 
        ///	(beat_num 14 kUnlockFreQMode freq_mode) 
        ///	(beat_campaign (3 15 1) kUnlockSuperSkill skill_nightmare) 
        ///	( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_unlocks {
            get {
                return ResourceManager.GetString("default_unlocks", resourceCulture);
            }
        }
    }
}
